### ISSUE TITLE
Documentation Additions

### ISSUE THREAD

**Issue by MonteD50** [UCSB-PSTAT/computing-wiki#6]
Overall the documentation was really smooth in terms of setting up the instance once the account was made. Some small remarks though:

- The step for creating an Access account username here (https://operations.access-ci.org/identity/new-user) should probably be combined with the documentation as a first step

- When creating a new Access account there should be a mention to use a university account (specifically UCSB) instead of selecting from scratch. This isn't too obvious in the documentation since the default image shows using the default Access account (not UCSB).

- It should be mentioned that the Access account creation at least for me didn't let me login for a couple days (kept throwing weird errors in the Access account (not the jetstream one)) so maybe a mention that this could take a couple days to process. 

- Also in the jetstreams part when allocating an instance when logging in, if they get an "Unauthorized access" message it means they need to be allocated resources using the access id created initially. 

- When creating an ssh key their should be separate instructions for windows computers on creating ssh key since running "code .ssh/.pub" doesn't do anything on windows so adding the general department tutorial on creating an ssh key might be useful: https://computing.pstat.ucsb.edu/docs/devcontainer/ssh-setup/#0

- Also after connecting to vscode, one more instruction could be to say to choose either (linux, windows, or mac)

- Also maybe a mention of the choice in choosing instance sources. Are we only allowed to choose the ucsb-pstat or can we choose other instance types?

Overall though pretty smooth documentation.

**Comment by 392781** [comment]
Here are my thoughts on potential fixes for the docs (feel free to let me know your opinion @Arm627) and also some questions for you:

> The step for creating an Access account username here (https://operations.access-ci.org/identity/new-user) should probably be combined with the documentation as a first step

This can be handled by adding an initial account creation step.

> When creating a new Access account there should be a mention to use a university account (specifically UCSB) instead of selecting from scratch. This isn't too obvious in the documentation since the default image shows using the default Access account (not UCSB).

Can you expand on this?  I don't believe email type poses an issue for account creation or usage.  That said, I can make an additional note in the docs for linking a school email to an account (which is an option ACCESS provides).

> It should be mentioned that the Access account creation at least for me didn't let me login for a couple days (kept throwing weird errors in the Access account (not the jetstream one)) so maybe a mention that this could take a couple days to process.

I think your particular case was unusual though I could be wrong.  That said, this could also be handled with an additional note inside the docs.

> Also in the jetstreams part when allocating an instance when logging in, if they get an "Unauthorized access" message it means they need to be allocated resources using the access id created initially.

Although this is mentioned in [step 5](https://computing.pstat.ucsb.edu/docs/computing/jetstream2/#1), you do make a good point.  This should probably be listed as a "warning" message.

> When creating an ssh key their should be separate instructions for windows computers on creating ssh key since running "code .ssh/.pub" doesn't do anything on windows so adding the general department tutorial on creating an ssh key might be useful: https://computing.pstat.ucsb.edu/docs/devcontainer/ssh-setup/#0

Can you verify that running `code <file location>` doesn't work (for any file)?  I've tested this on a Windows machine and it's worked in the past.  This is actually an issue with the documentation that I've written up a fix for but haven't published yet.  It should say `code .ssh/<KEY_NAME>.pub` but it doesn't because `<KEY_NAME>` gets treated as an HTML tag.  `code .ssh/.pub` shouldn't do anything since no file of that name exists there.

> Also after connecting to vscode, one more instruction could be to say to choose either (linux, windows, or mac)

Did this result in any unexpected behavior?  I debated on including that step but it's a bit problematic from a users perspective since they may be on one type of OS but their instance environment may be using a different OS (without them realizing it).

> Also maybe a mention of the choice in choosing instance sources. Are we only allowed to choose the ucsb-pstat or can we choose other instance types?

`ucsb-pstat` is currently the only one offered.  It's really meant to be a quick-start instance with R/Python and RStudio/Jupyterhub (I believe) bundled together.  The other instances that are there are created by other users for their own research needs so they're not intended for general purpose usage.  

There's a number of ways of handling this... We could make an additional tutorial talking about this in more depth, add a note expanding on what the instance is, or we could leave it up to the user.  I am leaning to the latter (with maybe a note added) since I would assume that if someone needs something more specific, they could at that point just boot up a fresh instance and install the packages they need (or create their own Dockerfile or edit the existing templates that we have).  Realistically, it falls under more advanced usage and at least for now, the aim is to create a simplified approach.

Anyway, let me know your thoughts on this.  I'll be making edits to the site soon.

**Comment by MonteD50** [comment]
Some comments on the comments :)

> This can be handled by adding an initial account creation step.

That sounds good to me

> Can you expand on this? I don't believe email type poses an issue for account creation or usage. That said, I can make an additional note in the docs for linking a school email to an account (which is an option ACCESS provides).

When creating an Access account the default is using an Access identity provider. I'm not too sure what this means so instead I searched up UC Santa Barbara and it was listed as a provider which I selected to use. This might not be obvious (its still not obvious to me if I should have or not) so just a quick mention of using the searching box and selecting UC Santa Barbara would be helpful I think.

> Can you verify that running code <file location> doesn't work (for any file)? I've tested this on a Windows machine and it's worked in the past. This is actually an issue with the documentation that I've written up a fix for but haven't published yet. It should say code .ssh/<KEY_NAME>.pub but it doesn't because <KEY_NAME> gets treated as an HTML tag. code .ssh/.pub shouldn't do anything since no file of that name exists there.

Ya fair, this does work on windows but it was a bit confusing without the <KEY_NAME> part especially since I'm not too experienced with ssh stuff. But basically a mention of the ssh documentation, maybe how to make or find the <KEY_NAME> and perhaps of (this is obvious in hindsight) running the terminal in administrator mode. 

> Did this result in any unexpected behavior? I debated on including that step but it's a bit problematic from a users perspective since they may be on one type of OS but their instance environment may be using a different OS (without them realizing it).

By default I chose Linux which worked perfectly but I've always been curious if I were to select a different option if it would work and someone else may be more comfortable in windows or mac and select that as an option which I have no idea if that will work or not.

> ucsb-pstat is currently the only one offered. It's really meant to be a quick-start instance with R/Python and RStudio/Jupyterhub (I believe) bundled together. The other instances that are there are created by other users for their own research needs so they're not intended for general purpose usage.

Ya your right for almost every scenario the ucsb-pstat should be fine. I was just curious I guess.

**Comment by 392781** [comment]
@Arm627 One more question: You mentioned needing to run terminal in administrator mode? I believe that SSH keys should've been stored under `C:\Users\<your_user_name>\.ssh\` which should not require administrative permissions to access. As far as I am aware, opening up Powershell/Command Prompt defaults to the `C:\Users\<your_user_name>\` location.

I would appreciate if you could verify!  I am trying to think of the best way possible to access the SSH keys since Windows makes it a pain to open up files with either no extension or an extension that doesn't correspond to a common file type (like `.pub` which literally just indicates a public key and not a file type).

**Comment by MonteD50** [comment]
@392781 Hi Ronald, yes your right looks like you don't need administrative mode to open the ssh file (not sure why I used it before)

**Comment by 392781** [comment]
Completed with commits 1c8ddadb87c8f9107c184a225b313135862bce3d, d2374bdec14631e8a117652bd84a528a1f0ae69b, and 0375274d6cfb2301ddbf7e26d1b0f82a8de0124e.
